---
- hosts: all
  become: true
  tasks:

  - name: Update all packages in Debian-based machines
    become: true
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day

  - name: Install software (Debian-based OS)
    apt:
      name: "{{ item }}"
      state: installed
      update_cache: yes
    with_items:
          - python3
          - python3-dev
          - python3-setuptools
          - htop
          - sysstat
          - atop
          - vim
          - wget
          - rsync 
          - netcat 
          - lldp
          - pwgen
          - jq
          

  - name: install pip3
    easy_install:
      name: pip
      executable: easy_install3

  - name: Install ansible 2.2
    pip:
      name: ansible
      version: 2.2
      executable: pip3
